server:
  port: 8080

spring:
  application:
    name: auth-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${auth0.domain}/"

auth0:
  audience: "https://wwt-test-task-api.example.com"
  domain: "dev-crfs6orqktz444bw.eu.auth0.com" 

jwt:
  secret: ${JWT_SECRET}